import localFont from "next/font/local";
import "./globals.css";

const vazirLocal = localFont({
    src: "./[seggestion]/assets/Vazirmatn-VariableFont_wght.ttf",
})


export const metadata = {
    title: "Create digi App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html dir="rtl" lang="fa" className={vazirLocal.className}>
        <body
        >
            {children}
        </body>
        </html>
    );
}