import { Vazirmatn , Geist_Mono } from "next/font/google";
import "./globals.css";

const vazirmatn = Vazirmatn({
    subsets: ["arabic"],
});



export const metadata = {
    title: "Create digi App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html dir="rtl" lang="fa" className={vazirmatn.className}>
        <body
        >
            {children}
        </body>
        </html>
    );
}