import Ads from "./[header]/ads";
import AdsBanner from "@/app/[ads_item]/adsBanner";
import Header from "@/app/[header]/header";
import Story from "@/app/[ads_item]/story";
import OnlineChat from "@/app/[fixItem]/onlineChat";
import SuperMarket from "@/app/[fixItem]/superMarket";

const Home = () => {
    return (
        <>
            <div className="fixed w-full top-0">
                <Ads/>
                <Header/>
            </div>
            <div className="mt-45">
                <Story />
                <AdsBanner/>
                <OnlineChat/>
                <SuperMarket/>
            </div>
            <div className="bg-gray-600">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, ducimus, est. Adipisci consequatur consequuntur distinctio ea esse fugit molestias necessitatibus nihil obcaecati reiciendis. Accusantium adipisci amet aperiam architecto asperiores assumenda, at aut blanditiis corporis cupiditate deleniti dolores ea eaque enim eos esse est eum inventore maxime minima minus natus nesciunt nihil perspiciatis quae quas qui rem rerum saepe sed sequi suscipit tempora tempore tenetur vel veniam vitae! Aperiam aut, consectetur culpa delectus eius eos eveniet impedit ipsam ipsum iste iusto, natus unde! A aliquam aliquid consectetur debitis deserunt ducimus eius error id impedit incidunt ipsam, ipsum labore, libero magni nostrum numquam obcaecati omnis possimus praesentium quaerat quasi ratione recusandae rem sed vel. Dolores eum incidunt ipsam pariatur velit. Eveniet fugiat magni modi porro? Accusamus alias blanditiis dolor dolorem eos esse et eveniet, illo incidunt iste laboriosam minima omnis placeat quasi recusandae, reiciendis similique. Blanditiis, consequatur delectus doloremque eos fugit incidunt ipsum iure libero natus possimus quaerat quos repellendus saepe sequi tempore totam ut? Adipisci aliquam amet cumque delectus deserunt dolore doloremque ducimus earum exercitationem fuga fugit harum labore, maxime modi odit officiis quae quaerat, quas quia ratione similique vero vitae voluptatum! Deserunt eaque harum, molestias mollitia recusandae voluptate? Maxime, quod!d</p>

            </div>

          </>
    )
}

export default Home